# Generated by Django 3.2.25 on 2024-09-19 03:11

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Operation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('link_portal_negocio', models.URLField(blank=True, null=True)),
                ('ejecutivo_negocio', models.CharField(max_length=255)),
                ('nombre_cliente', models.CharField(max_length=255)),
                ('nombre_operacion', models.CharField(max_length=255)),
                ('pais', models.CharField(max_length=255)),
                ('instrumento_financiero', models.CharField(max_length=255)),
                ('tipo_cliente', models.CharField(max_length=255)),
                ('monto_miles', models.FloatField()),
                ('moneda_local', models.CharField(max_length=255)),
                ('calificacion_externa_cliente', models.CharField(max_length=255)),
                ('rating_cliente', models.CharField(max_length=255)),
                ('calificacion_interna_cliente', models.CharField(max_length=255)),
                ('necesidad_cliente', models.CharField(max_length=255)),
                ('competitividad_caf', models.CharField(max_length=255)),
                ('experiencia_caf', models.CharField(max_length=255)),
                ('descripcion', models.TextField()),
                ('actividad_principal', models.CharField(max_length=255)),
                ('segmento_operacion', models.CharField(max_length=255)),
                ('sector_economico', models.CharField(max_length=255)),
                ('sub_sector_economico', models.CharField(max_length=255)),
                ('area_actuacion', models.CharField(max_length=255)),
                ('agendas_misionales', models.CharField(max_length=255)),
                ('agendas_transversales_verdes', models.CharField(max_length=255)),
                ('agendas_transversales_b4', models.CharField(max_length=255)),
                ('agendas_transversales_b5', models.CharField(max_length=255)),
                ('agendas_transversales_b6', models.CharField(max_length=255)),
                ('ods_1', models.CharField(max_length=255)),
                ('ods_2', models.CharField(max_length=255)),
                ('ods_3', models.CharField(max_length=255)),
                ('ods_4', models.CharField(max_length=255)),
                ('adicionalidad_cubrir_brechas', models.CharField(max_length=255)),
                ('adicionalidad_mitigar_riesgos', models.CharField(max_length=255)),
                ('adicionalidad_mejorar_condiciones', models.CharField(max_length=255)),
                ('adicionalidad_movilizar_recursos', models.CharField(max_length=255)),
                ('adicionalidad_instrumento_innovador', models.CharField(max_length=255)),
                ('adicionalidad_conocimiento', models.CharField(max_length=255)),
                ('fecha_tentativa_desembolso', models.DateField()),
                ('plazo_operacion', models.FloatField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operations', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Corporativo',
            fields=[
                ('operation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='myapp.operation')),
                ('corporativo_robustez_razon_liquidez', models.CharField(max_length=255)),
                ('corporativo_robustez_estructura_financiera', models.CharField(max_length=255)),
                ('corporativo_robustez_ffo', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='CorporativoEstructuradoFinancieras',
            fields=[
                ('operation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='myapp.operation')),
                ('corpestfin_riesgo', models.CharField(max_length=255)),
                ('corpestfin_spread_pb', models.FloatField()),
                ('corpestfin_meses_gracia', models.FloatField()),
                ('corpestfin_comision_estructuracion', models.FloatField()),
                ('corpestfin_comision_anual', models.FloatField()),
                ('corpestfin_robustez_cliente', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='CorporativoFinancieras',
            fields=[
                ('operation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='myapp.operation')),
                ('corpfin_robustez_gerencia', models.CharField(max_length=255)),
                ('corpfin_robustez_posicion_mercado', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='FinanciamientoEstructurado',
            fields=[
                ('operation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='myapp.operation')),
                ('estructurado_contratacion_ingresos', models.CharField(max_length=255)),
                ('estructurado_capex_garantizado', models.CharField(max_length=255)),
                ('estructurado_financiamiento_identificado', models.CharField(max_length=255)),
                ('estructurado_permisos', models.CharField(max_length=255)),
                ('estructurado_estructura_ingresos', models.CharField(max_length=255)),
                ('estructurado_ingresos_publicos', models.CharField(max_length=255)),
                ('estructurado_experiencia_epecista', models.CharField(max_length=255)),
                ('estructurado_experiencia_operador', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='InstitucionesFinancieras',
            fields=[
                ('operation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='myapp.operation')),
                ('financieras_robustez_razon_liquidez', models.CharField(max_length=255)),
                ('financieras_morosidad', models.CharField(max_length=255)),
                ('financieras_solvencia', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='InversionesPatrimoniales',
            fields=[
                ('operation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='myapp.operation')),
                ('patrimoniales_rentabilidad_esperada', models.FloatField()),
                ('patrimoniales_tipo_fondo', models.CharField(max_length=255)),
                ('patrimoniales_antecedentes_gestor', models.CharField(max_length=255)),
                ('patrimoniales_experiencia_sector', models.CharField(max_length=255)),
                ('patrimoniales_experiencia_region', models.CharField(max_length=255)),
                ('patrimoniales_experiencia_equipo', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='OperationScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adicionalidad_e_impacto', models.FloatField()),
                ('robustez_cliente', models.FloatField()),
                ('raroc', models.FloatField()),
                ('madurez_proyecto', models.FloatField()),
                ('vsp_score', models.FloatField()),
                ('operation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='score', to='myapp.operation')),
            ],
        ),
    ]
